SWW_WEB: https://supplierwebwork.com/AccountPortal/Login

TRUE_EP_WEB: https://ep.pantavanij.com/true/Firstpage.action
MTL_EP_WEB: https://muangthaiep.pantavanij.com/Firstpage.action
MTL_EP_HOME: http://muangthaiep.pantavanij.com/PortalHome.action
#Invoice
EINVOICE_URL_WEB:    https://invoice-portal.oneplanetapp.com
BUYER_APPROVE_URI:    /BuyerApprove
BUYER_STATUS_URI:    /BuyerStatus
BUYER_APPROVE_CNDN_URI: /ApproveCreditNote
BUYER_MANAGE_CNDN_URI: /ManageCreditNote

#Best Supply 
SWW_WEB: https://supplierwebwork.com/AccountPortal/Login

#EP
CPALL_EP_WEB: https://cpallep.pantavanij.com/Firstpage.action